name             'installerz'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'installs stuff'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'homebrew'
depends          'osx_pkg'
depends          'dmg'
depends          'mac_os_x'
