ZSH=$HOME/.oh-my-zsh

ZSH_THEME="marpaia"

plugins=(git, go, history-substring-search, jira, pip, python, ruby, rvm, urltools, web-search, zsh-syntax-highlighting)

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

source $ZSH/oh-my-zsh.sh
