ZSH=$HOME/.oh-my-zsh

ZSH_THEME="marpaia"

plugins=(colored-man, encode64, extract, git, github, go, history-substring-search, jira, osx, pip, python, ruby, rvm, urltools, web-search, zsh-syntax-highlighting)

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

source $ZSH/oh-my-zsh.sh
