ZSH=$HOME/.oh-my-zsh

ZSH_THEME="marpaia"

plugins=(battery brew bundler capistrano colored-man copydir copyfile cp dircycle django encode64 extract gem git git-extras git-remote-branch gitfast github go golang heroku history-substring-search jira jruby knife laravel last-working-dir lol node npm osx per-directory-history pip profiles python rails rails3 rails4 rake rbenv redis-cli rsync ruby rvm sublime urltools vagrant web-search)

source $ZSH/oh-my-zsh.sh
